[package]
name = "susycore"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]
name = "susycore"
path = "src/lib.rs"

[dependencies]
env_logger = "0.11.10"
jni = { workspace = true, features = ["invocation"] }
log = "0.4.29"
once_cell = "1.21.4"
ordered-float = "5.3.0"
rapier3d = { version = "0.32", features = ["parallel", "serde-serialize", "simd-stable"] }

